export enum AuthErrorCode {
  INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  EMAIL_ALREADY_REGISTERED = 'AUTH_EMAIL_ALREADY_REGISTERED',

  TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  REFRESH_REVOKED = 'AUTH_REFRESH_REVOKED',

  OTP_INVALID = 'AUTH_OTP_INVALID',
  OTP_EXPIRED = 'AUTH_OTP_EXPIRED',
  OTP_TOO_MANY_REQUESTS = 'AUTH_OTP_TOO_MANY_REQUESTS',

  OAUTH_FAILED = 'AUTH_OAUTH_FAILED',
  OAUTH_CONFLICT = 'AUTH_OAUTH_CONFLICT',

  INTERNAL = 'AUTH_INTERNAL_ERROR',
}
